baseurl = ""
title = "Austin's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg.jpg"
  SEOTitle = "Austin Halvorsen | Blog"
  description = "A place to keep my lifes moments, both in career and personal"
  keyword = ""
  slogan = ""

  image_404 = "img/404-bg.jpg"
  title_404 = ":("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/profile.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true 
  email          = "austinhalvorsen@gmail.com"
  facebook      = "https://www.facebook.com/austin.halvorsen"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/AustinHal"
  linkedin       = "https://www.linkedin.com/in/ahalvo/"
  stackoverflow  = "https://stackoverflow.com/users/9727606/austinhal"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/austinhal"
  #wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  title = "My Test"
  href =  "uninformedpriors.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesh"
  href =  "http://www.servicemesh.cn"
  [[params.bookmark_link]]
  title = "Awesome Service Mesh"
  href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  [[params.bookmark_link]]
  title =  "Image Compression"
  href = "https://tinypng.com"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 